# Generated by Django 4.2.2 on 2023-06-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UniversityConnect", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="name_en",
            field=models.CharField(default="English Name", max_length=100),
        ),
        migrations.AddField(
            model_name="curso",
            name="description_en",
            field=models.TextField(default="English Description", max_length=350),
        ),
        migrations.AddField(
            model_name="curso",
            name="tittle_en",
            field=models.CharField(default="English Name", max_length=100),
        ),
        migrations.AddField(
            model_name="formacao",
            name="name_en",
            field=models.CharField(default="English Name", max_length=100),
        ),
        migrations.AddField(
            model_name="nivelcurso",
            name="name_en",
            field=models.CharField(default="English Name", max_length=100),
        ),
        migrations.AlterField(
            model_name="curso",
            name="descricao",
            field=models.TextField(max_length=350),
        ),
    ]
