# Generated by Django 4.2.2 on 2023-07-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UniversityConnect", "0003_curso_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="mini_descricao",
            field=models.TextField(default="English Description", max_length=130),
        ),
        migrations.AddField(
            model_name="curso",
            name="mini_description_en",
            field=models.TextField(default="English Description", max_length=130),
        ),
        migrations.AlterField(
            model_name="curso",
            name="descricao",
            field=models.TextField(max_length=550),
        ),
    ]
