# Generated by Django 4.2.2 on 2023-07-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UniversityConnect", "0005_alter_curso_descricao_alter_curso_description_en"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="descricao",
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="curso",
            name="description_en",
            field=models.TextField(default="English Description", max_length=1000),
        ),
    ]
