# Generated by Django 4.2.2 on 2023-07-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UniversityConnect", "0006_alter_curso_descricao_alter_curso_description_en"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="descricao",
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="curso",
            name="description_en",
            field=models.TextField(default="English Description", max_length=2000),
        ),
        migrations.AlterField(
            model_name="curso",
            name="mini_descricao",
            field=models.TextField(default="English Description", max_length=255),
        ),
        migrations.AlterField(
            model_name="curso",
            name="mini_description_en",
            field=models.TextField(default="English Description", max_length=255),
        ),
    ]
