# Generated by Django 4.2.2 on 2023-07-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "UniversityConnect",
            "0007_alter_curso_descricao_alter_curso_description_en_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="image",
            field=models.ImageField(
                blank=True, default="", upload_to="cursos/cover/%Y/%m/%d/"
            ),
        ),
    ]
