# Generated by Django 4.2.2 on 2023-07-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UniversityConnect", "0008_alter_curso_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="time_course_en",
            field=models.CharField(default="0 years", max_length=100),
        ),
    ]
