# Generated by Django 4.2.2 on 2023-09-13 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("UniversityConnect", "0009_curso_time_course_en"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Categoria",
            new_name="Category",
        ),
        migrations.RenameModel(
            old_name="Curso",
            new_name="Course",
        ),
        migrations.RenameModel(
            old_name="NivelCurso",
            new_name="CourseLevel",
        ),
        migrations.RenameModel(
            old_name="Formacao",
            new_name="Education",
        ),
    ]
