# Generated by Django 4.2.2 on 2023-09-13 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "UniversityConnect",
            "0010_rename_categoria_category_rename_curso_course_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="courselevel",
            old_name="nome",
            new_name="name",
        ),
    ]
