# Generated by Django 4.2.2 on 2023-09-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UniversityConnect", "0011_rename_nome_courselevel_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="nome",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="categoria",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="botao",
            new_name="class_type",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="nivel_curso",
            new_name="course_level",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="carga_horaria",
            new_name="course_load",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="tempo_curso",
            new_name="course_time",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="descricao",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="formacao",
            new_name="education",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="mini_descricao",
            new_name="mini_description",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="mensalidade",
            new_name="monthly_course_fee",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="tipo_aula",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="education",
            old_name="nome",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="course",
            name="titulo",
        ),
        migrations.AddField(
            model_name="course",
            name="link",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
