# Generated by Django 4.2.2 on 2023-09-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UniversityConnect", "0012_rename_nome_category_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                ("biography", models.CharField(max_length=400)),
                ("biography_en", models.CharField(max_length=400)),
                ("birth_date", models.PositiveIntegerField()),
                ("death_date", models.PositiveIntegerField(blank=True, default=None)),
            ],
        ),
    ]
