# Generated by Django 4.2.2 on 2023-09-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UniversityConnect", "0013_exstudent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exstudent",
            name="biography",
            field=models.CharField(max_length=800),
        ),
    ]
