# Generated by Django 4.2.2 on 2023-09-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UniversityConnect", "0014_alter_exstudent_biography"),
    ]

    operations = [
        migrations.AddField(
            model_name="exstudent",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="ex_students/cover/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(
                blank=True, default="", upload_to="courses/cover/%Y/%m/%d/"
            ),
        ),
    ]
