# Generated by Django 4.2.2 on 2023-09-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UniversityConnect", "0017_alter_new_mini_decription_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="new",
            name="text_en",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
