# Generated by Django 4.2.2 on 2023-09-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UniversityConnect", "0018_new_text_en"),
    ]

    operations = [
        migrations.CreateModel(
            name="Places",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("tittle_en", models.CharField(default="English Name", max_length=100)),
                (
                    "mini_description",
                    models.TextField(default="English Description", max_length=255),
                ),
                (
                    "mini_description_en",
                    models.TextField(default="English Description", max_length=255),
                ),
                ("iframe_link", models.CharField(max_length=500)),
                ("link", models.CharField(max_length=500)),
            ],
        ),
    ]
