# Generated by Django 4.2.2 on 2023-09-20 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("UniversityConnect", "0019_places"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="tittle_en",
            new_name="title_en",
        ),
    ]
