# Generated by Django 4.2.2 on 2023-09-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "UniversityConnect",
            "0021_alter_course_description_alter_course_description_en",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="exstudent",
            name="biography",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="exstudent",
            name="biography_en",
            field=models.TextField(),
        ),
    ]
